{
  "hash": "e6dfcae4a91b01855702fba738bd7300",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\nauthor: \"Annmary Jose\"\n---\n\n\n# Assignment\n\n1.  Draw the DAG for parking slot\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_ce3f88147c13f5ccd8930ea5e185b905'}\n\n```{.r .cell-code}\n#install and load necessary package\nlibrary(\"tidyverse\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n#> ✔ dplyr     1.1.4     ✔ readr     2.1.4\n#> ✔ forcats   1.0.0     ✔ stringr   1.5.1\n#> ✔ ggplot2   3.4.4     ✔ tibble    3.2.1\n#> ✔ lubridate 1.9.3     ✔ tidyr     1.3.0\n#> ✔ purrr     1.0.2     \n#> ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n#> ✖ dplyr::filter() masks stats::filter()\n#> ✖ dplyr::lag()    masks stats::lag()\n#> ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\n#install.packages(\"dagitty\")\n#install.packages(\"ggdag\")\nlibrary(dagitty)\nlibrary(ggdag)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> \n#> Attaching package: 'ggdag'\n#> \n#> The following object is masked from 'package:stats':\n#> \n#>     filter\n```\n:::\n:::\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_446eaceec39e91b51ba2570f607a2019'}\n\n```{.r .cell-code}\n# with confounder\ndag <- dagify(\n  parkingslot ~ location,\n  sales ~ location,\n  sales ~ parkingslot,\n  coords = list(x = c(parkingslot = 1, sales = 3, location = 2),\n                y = c(parkingslot = 1, sales = 1, location = 2)),\n  labels = c(\"ParkingSpots\" = \"A\")\n)\n\n# Plot DAG\nggdag(dag, text = F) +\n  geom_dag_point(color = \"green\")+\n  geom_dag_text(color = NA) +\n  geom_dag_edges(edge_color = \"yellow\") +\n  geom_dag_label_repel(aes(label = name))\n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n2.  Load the data file `customer_sat.rds`.\n\n\n    ::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_d14fd6738255afe91dbd88dc0d3c3516'}\n    \n    ```{.r .cell-code}\n    data <- readRDS(\"../../Causal_Data_Science_Data/customer_sat.rds\")\n    view(data)\n    ```\n    :::\n\n\n    1.  regress `satisfaction` on `follow_ups`\n\n\n    ::: {.cell hash='05_dag_cache/html/unnamed-chunk-4_1d281a105f37c108e4c50dff3275526c'}\n    \n    ```{.r .cell-code}\n    regression_1 <- lm(satisfaction ~ follow_ups, data = data)\n    \n    summary(regression_1)\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    ```\n    #> \n    #> Call:\n    #> lm(formula = satisfaction ~ follow_ups, data = data)\n    #> \n    #> Residuals:\n    #>     Min      1Q  Median      3Q     Max \n    #> -12.412  -5.257   1.733   4.506  12.588 \n    #> \n    #> Coefficients:\n    #>             Estimate Std. Error t value Pr(>|t|)    \n    #> (Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\n    #> follow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n    #> ---\n    #> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n    #> \n    #> Residual standard error: 7.923 on 13 degrees of freedom\n    #> Multiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \n    #> F-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n    ```\n    :::\n    :::\n\n```{=html}\n<!-- -->\n```\n\n2.  regress `satisfaction` on `follow_ups` and account for `subscription`\n\n\n    ::: {.cell hash='05_dag_cache/html/unnamed-chunk-5_25eeb42944d5798c2fcfa499ccc6818f'}\n    \n    ```{.r .cell-code}\n    regression_2 <- lm(satisfaction ~ follow_ups + subscription, data = data)\n    \n    summary(regression_2)\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    ```\n    #> \n    #> Call:\n    #> lm(formula = satisfaction ~ follow_ups + subscription, data = data)\n    #> \n    #> Residuals:\n    #>     Min      1Q  Median      3Q     Max \n    #> -4.3222 -2.1972  0.3167  2.2667  3.9944 \n    #> \n    #> Coefficients:\n    #>                      Estimate Std. Error t value Pr(>|t|)    \n    #> (Intercept)           26.7667     6.6804   4.007  0.00206 ** \n    #> follow_ups             2.1944     0.7795   2.815  0.01682 *  \n    #> subscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\n    #> subscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n    #> ---\n    #> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n    #> \n    #> Residual standard error: 2.958 on 11 degrees of freedom\n    #> Multiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \n    #> F-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n    ```\n    :::\n    :::\n\n\n3.   Compare the coefficients and find a possible explanation.\n\n-   In the first regression,the coefficient for follow_ups is negative( -3.3093). This implies that for each additional follow-up, satisfaction decreases by 3.3093 units.\n\n-   In the second regression,the coefficient for follow_ups is now positive (2.1944), suggesting that, on average, satisfaction increases by 2.1944 units for each additional follow-up.\n\n4.  Plot the data. \n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-6_f7920007549e26d8d5f7bf03437324fa'}\n\n```{.r .cell-code}\nnot_cond <- ggplot(data, aes(x = satisfaction, y = follow_ups)) +\n  geom_point(alpha =0.8) +\n  stat_smooth(method = \"lm\", se = F)\n\n  \ncond <- ggplot(data, aes(x = satisfaction, y = follow_ups,\n                            color = subscription)) +\n  geom_point(alpha =0.8) +\n  stat_smooth(method = \"lm\", se = F) +\n  theme(legend.position = \"right\")\n\n# Plot both\nnot_cond\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncond\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}